<<<<<<< HEAD
title: Bo Yang's Homepage
page-top-title: Bo Yang
top-section-bg-text: Welcome to my Homepage!
home-subtitle: Name&ensp;|&ensp;杨博
copyright-text: '&copy; Bo Yang 2023-2025. All Rights Reserved.'
=======
title: Yourname's Homepage
page-top-title: Yourname
top-section-bg-text: Be what you wanna be
home-subtitle: Yourname&ensp;|&ensp;上杉绘梨衣
copyright-text: '&copy; Yourname 2023-2025. All Rights Reserved.'
>>>>>>> 65c2f4c245456d546294e5c2b3e6ff2384fc1ee2
